services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./hello_world.py"
    depends_on:
      - mysql
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'new_schema'
      MYSQL_ROOT_PASSWORD: "Root"
    ports:
      - '3306:3306'